import type { WeaponConfig, WeaponId } from './WeaponTypes';

/**
 * Weapon balance data. Everything a designer would want to tweak lives here —
 * no gameplay numbers are hidden in the systems code.
 */

export const PISTOL: WeaponConfig = {
  id: 'pistol',
  name: 'M9 Sidearm',
  category: 'PISTOL',
  slot: 1,

  damage: 28,
  headshotMultiplier: 2.0,
  limbMultiplier: 0.85,
  pellets: 1,
  pelletSpread: 0,
  falloffStart: 18,
  falloffEnd: 55,
  minDamageScale: 0.55,
  penetration: 0,
  penetrationDamageScale: 0.5,
  muzzleVelocity: 380,

  rpm: 450,
  fireModes: ['semi'],
  burstCount: 1,
  burstDelay: 0.07,
  actionType: 'slide',
  cycleTime: 0,

  magSize: 15,
  reserveAmmo: 90,
  maxReserveAmmo: 120,
  reloadTime: 1.5,
  reloadEmptyTime: 2.1,
  shellReload: false,
  shellReloadTime: 0,

  drawTime: 0.4,
  holsterTime: 0.28,
  adsTime: 0.16,
  adsFovScale: 0.82,
  adsMoveScale: 0.62,
  weightMoveScale: 1.0,

  spread: {
    hip: 1.9,
    ads: 0.22,
    moving: 1.6,
    jumping: 4.0,
    crouchScale: 0.7,
    perShot: 0.55,
    recovery: 5.5,
    max: 5.0,
  },
  recoil: {
    vertical: 0.95,
    horizontal: 0.34,
    randomness: 0.4,
    recovery: 9,
    permanence: 0.08,
    kickback: 0.022,
    modelPitch: 7,
    shake: 0.4,
  },
  viewModel: {
    hipOffset: [0.0, -0.005, 0.0],
    hipRotation: [0, 0, 0],
    adsDistance: 0.28,
    swayScale: 1.15,
    scale: 1,
  },

  audio: {
    gain: 0.62,
    bodyFreq: 190,
    bodyEndFreq: 62,
    bodyDecay: 0.11,
    crackDecay: 0.1,
    crackFreqStart: 6500,
    crackFreqEnd: 420,
    crackHighpass: 320,
    tail: 0.3,
    grit: 0.3,
  },
  flashScale: 0.75,
  flashColor: 0xffcc66,
  tracerColor: 0xffd27a,
  tracerWidth: 0.016,
  tracerChance: 0.4,
  ejectsShells: true,
  shellScale: 0.85,
  flashLightIntensity: 6,
  crosshairGap: 7,
  description: 'Reliable semi-automatic sidearm. Fast to draw, forgiving recoil, limited range.',
};

export const SMG: WeaponConfig = {
  id: 'smg',
  name: 'MP-9 Vector',
  category: 'SMG',
  slot: 4,

  damage: 20,
  headshotMultiplier: 1.6,
  limbMultiplier: 0.9,
  pellets: 1,
  pelletSpread: 0,
  falloffStart: 12,
  falloffEnd: 38,
  minDamageScale: 0.45,
  penetration: 0,
  penetrationDamageScale: 0.45,
  muzzleVelocity: 400,

  rpm: 950,
  fireModes: ['auto', 'semi'],
  burstCount: 1,
  burstDelay: 0.06,
  actionType: 'gas',
  cycleTime: 0,

  magSize: 32,
  reserveAmmo: 192,
  maxReserveAmmo: 256,
  reloadTime: 1.75,
  reloadEmptyTime: 2.4,
  shellReload: false,
  shellReloadTime: 0,

  drawTime: 0.48,
  holsterTime: 0.32,
  adsTime: 0.2,
  adsFovScale: 0.86,
  adsMoveScale: 0.66,
  weightMoveScale: 0.98,

  spread: {
    hip: 2.6,
    ads: 0.5,
    moving: 1.5,
    jumping: 4.5,
    crouchScale: 0.75,
    perShot: 0.34,
    recovery: 7.5,
    max: 7.0,
  },
  recoil: {
    vertical: 0.52,
    horizontal: 0.4,
    randomness: 0.55,
    recovery: 11,
    permanence: 0.12,
    kickback: 0.014,
    modelPitch: 4,
    shake: 0.3,
    pattern: [
      [0, 0.5],
      [0.04, 0.55],
      [-0.06, 0.6],
      [0.1, 0.55],
      [-0.14, 0.5],
      [0.18, 0.45],
      [-0.2, 0.42],
      [0.24, 0.4],
    ],
  },
  viewModel: {
    hipOffset: [0.005, 0, -0.01],
    hipRotation: [0, 0, 0],
    adsDistance: 0.3,
    swayScale: 1.0,
    scale: 1,
  },

  audio: {
    gain: 0.5,
    bodyFreq: 170,
    bodyEndFreq: 70,
    bodyDecay: 0.075,
    crackDecay: 0.07,
    crackFreqStart: 7200,
    crackFreqEnd: 520,
    crackHighpass: 420,
    tail: 0.22,
    grit: 0.35,
  },
  flashScale: 0.7,
  flashColor: 0xffd08a,
  tracerColor: 0xffe08a,
  tracerWidth: 0.014,
  tracerChance: 0.3,
  ejectsShells: true,
  shellScale: 0.8,
  flashLightIntensity: 5,
  crosshairGap: 9,
  description: 'High rate of fire, low recoil, poor range. Excellent for close-quarters work.',
};

export const RIFLE: WeaponConfig = {
  id: 'rifle',
  name: 'AR-15 Carbine',
  category: 'RIFLE',
  slot: 5,

  damage: 33,
  headshotMultiplier: 1.9,
  limbMultiplier: 0.85,
  pellets: 1,
  pelletSpread: 0,
  falloffStart: 40,
  falloffEnd: 95,
  minDamageScale: 0.6,
  penetration: 2,
  penetrationDamageScale: 0.6,
  muzzleVelocity: 880,

  rpm: 640,
  fireModes: ['auto', 'burst', 'semi'],
  burstCount: 3,
  burstDelay: 0.09,
  actionType: 'gas',
  cycleTime: 0,

  magSize: 30,
  reserveAmmo: 180,
  maxReserveAmmo: 240,
  reloadTime: 2.05,
  reloadEmptyTime: 2.75,
  shellReload: false,
  shellReloadTime: 0,

  drawTime: 0.55,
  holsterTime: 0.36,
  adsTime: 0.26,
  adsFovScale: 0.72,
  adsMoveScale: 0.55,
  weightMoveScale: 0.94,

  spread: {
    hip: 2.4,
    ads: 0.16,
    moving: 1.8,
    jumping: 5.0,
    crouchScale: 0.65,
    perShot: 0.42,
    recovery: 6.5,
    max: 6.5,
  },
  recoil: {
    vertical: 0.9,
    horizontal: 0.34,
    randomness: 0.45,
    recovery: 8.5,
    permanence: 0.18,
    kickback: 0.02,
    modelPitch: 6,
    shake: 0.5,
    pattern: [
      [0, 0.85],
      [-0.05, 0.95],
      [0.08, 1.0],
      [0.16, 0.9],
      [0.24, 0.8],
      [0.1, 0.75],
      [-0.18, 0.7],
      [-0.3, 0.65],
      [-0.36, 0.6],
      [-0.24, 0.6],
      [0.06, 0.55],
      [0.3, 0.55],
    ],
  },
  viewModel: {
    hipOffset: [0.0, 0.0, -0.02],
    hipRotation: [0, 0, 0],
    adsDistance: 0.34,
    swayScale: 0.9,
    scale: 1,
  },

  audio: {
    gain: 0.78,
    bodyFreq: 230,
    bodyEndFreq: 58,
    bodyDecay: 0.14,
    crackDecay: 0.12,
    crackFreqStart: 8200,
    crackFreqEnd: 380,
    crackHighpass: 280,
    tail: 0.45,
    grit: 0.45,
  },
  flashScale: 1.0,
  flashColor: 0xffbb55,
  tracerColor: 0xfff0a0,
  tracerWidth: 0.018,
  tracerChance: 0.45,
  ejectsShells: true,
  shellScale: 1.0,
  flashLightIntensity: 9,
  crosshairGap: 8,
  description: 'The all-rounder. Selectable fire modes, strong mid-range damage, learnable recoil pattern.',
};

export const SNIPER: WeaponConfig = {
  id: 'sniper',
  name: 'M40 Marksman',
  category: 'SNIPER',
  slot: 7,

  damage: 125,
  headshotMultiplier: 2.4,
  limbMultiplier: 0.7,
  pellets: 1,
  pelletSpread: 0,
  falloffStart: 150,
  falloffEnd: 320,
  minDamageScale: 0.85,
  penetration: 3,
  penetrationDamageScale: 0.75,
  muzzleVelocity: 1100,

  rpm: 50,
  fireModes: ['semi'],
  burstCount: 1,
  burstDelay: 0,
  actionType: 'bolt',
  cycleTime: 0.95,

  magSize: 5,
  reserveAmmo: 30,
  maxReserveAmmo: 45,
  reloadTime: 2.9,
  reloadEmptyTime: 3.5,
  shellReload: false,
  shellReloadTime: 0,

  drawTime: 0.75,
  holsterTime: 0.45,
  adsTime: 0.4,
  adsFovScale: 0.28,
  scopeFov: 12,
  adsMoveScale: 0.35,
  weightMoveScale: 0.86,

  spread: {
    hip: 6.5,
    ads: 0.012,
    moving: 3.0,
    jumping: 7.0,
    crouchScale: 0.5,
    perShot: 1.4,
    recovery: 3.0,
    max: 9.0,
  },
  recoil: {
    vertical: 3.4,
    horizontal: 0.7,
    randomness: 0.35,
    recovery: 4.5,
    permanence: 0.3,
    kickback: 0.06,
    modelPitch: 14,
    shake: 1.3,
  },
  viewModel: {
    hipOffset: [0.01, -0.01, -0.04],
    hipRotation: [0, 0, 0],
    adsDistance: 0.4,
    swayScale: 0.7,
    scale: 1,
  },

  audio: {
    gain: 0.95,
    bodyFreq: 260,
    bodyEndFreq: 42,
    bodyDecay: 0.24,
    crackDecay: 0.2,
    crackFreqStart: 9000,
    crackFreqEnd: 260,
    crackHighpass: 200,
    tail: 0.85,
    grit: 0.5,
  },
  flashScale: 1.35,
  flashColor: 0xffa844,
  tracerColor: 0xfff4c8,
  tracerWidth: 0.024,
  tracerChance: 1.0,
  ejectsShells: true,
  shellScale: 1.25,
  flashLightIntensity: 14,
  crosshairGap: 12,
  description: 'Bolt-action precision rifle. One-shot lethal, punishing between shots, scoped optics.',
};

export const SHOTGUN: WeaponConfig = {
  id: 'shotgun',
  name: 'M870 Breacher',
  category: 'SHOTGUN',
  slot: 9,

  damage: 13,
  headshotMultiplier: 1.4,
  limbMultiplier: 0.9,
  pellets: 9,
  pelletSpread: 2.6,
  falloffStart: 8,
  falloffEnd: 26,
  minDamageScale: 0.12,
  penetration: 0,
  penetrationDamageScale: 0.3,
  muzzleVelocity: 400,

  rpm: 80,
  fireModes: ['semi'],
  burstCount: 1,
  burstDelay: 0,
  actionType: 'pump',
  cycleTime: 0.62,

  magSize: 8,
  reserveAmmo: 48,
  maxReserveAmmo: 64,
  reloadTime: 0.55,
  reloadEmptyTime: 0.55,
  shellReload: true,
  shellReloadTime: 0.46,

  drawTime: 0.62,
  holsterTime: 0.4,
  adsTime: 0.28,
  adsFovScale: 0.88,
  adsMoveScale: 0.6,
  weightMoveScale: 0.92,

  spread: {
    hip: 1.4,
    ads: 0.6,
    moving: 1.0,
    jumping: 3.0,
    crouchScale: 0.85,
    perShot: 0.5,
    recovery: 4.0,
    max: 4.0,
  },
  recoil: {
    vertical: 3.0,
    horizontal: 0.9,
    randomness: 0.4,
    recovery: 5.5,
    permanence: 0.22,
    kickback: 0.055,
    modelPitch: 13,
    shake: 1.1,
  },
  viewModel: {
    hipOffset: [0.0, -0.005, -0.03],
    hipRotation: [0, 0, 0],
    adsDistance: 0.32,
    swayScale: 0.85,
    scale: 1,
  },

  audio: {
    gain: 0.9,
    bodyFreq: 150,
    bodyEndFreq: 38,
    bodyDecay: 0.22,
    crackDecay: 0.17,
    crackFreqStart: 5200,
    crackFreqEnd: 200,
    crackHighpass: 150,
    tail: 0.6,
    grit: 0.6,
  },
  flashScale: 1.5,
  flashColor: 0xff9a3c,
  tracerColor: 0xffc07a,
  tracerWidth: 0.012,
  tracerChance: 0.15,
  ejectsShells: true,
  shellScale: 1.4,
  flashLightIntensity: 12,
  crosshairGap: 18,
  description: 'Pump-action buckshot. Devastating up close, useless past twenty metres.',
};

export const MACHINE_PISTOL: WeaponConfig = {
  id: 'machinePistol',
  name: 'TMP-18 Machine Pistol',
  category: 'MACH. PISTOL',
  slot: 2,

  damage: 16,
  headshotMultiplier: 1.5,
  limbMultiplier: 0.9,
  pellets: 1,
  pelletSpread: 0,
  falloffStart: 8,
  falloffEnd: 25,
  minDamageScale: 0.4,
  penetration: 0,
  penetrationDamageScale: 0.4,
  muzzleVelocity: 360,

  rpm: 1200,
  fireModes: ['auto', 'semi'],
  burstCount: 1,
  burstDelay: 0.05,
  actionType: 'slide',
  cycleTime: 0,

  magSize: 20,
  reserveAmmo: 160,
  maxReserveAmmo: 200,
  reloadTime: 1.4,
  reloadEmptyTime: 1.9,
  shellReload: false,
  shellReloadTime: 0,

  drawTime: 0.34,
  holsterTime: 0.24,
  adsTime: 0.14,
  adsFovScale: 0.86,
  adsMoveScale: 0.7,
  weightMoveScale: 1.03,

  spread: {
    hip: 3.6,
    ads: 1.0,
    moving: 1.9,
    jumping: 5.0,
    crouchScale: 0.8,
    perShot: 0.5,
    recovery: 9,
    max: 8.5,
  },
  recoil: {
    vertical: 0.55,
    horizontal: 0.6,
    randomness: 0.7,
    recovery: 12,
    permanence: 0.1,
    kickback: 0.013,
    modelPitch: 5,
    shake: 0.28,
  },
  viewModel: {
    hipOffset: [0.0, -0.005, 0.0],
    hipRotation: [0, 0, 0],
    adsDistance: 0.3,
    swayScale: 1.2,
    scale: 1,
  },

  audio: {
    gain: 0.44,
    bodyFreq: 165,
    bodyEndFreq: 74,
    bodyDecay: 0.06,
    crackDecay: 0.055,
    crackFreqStart: 7600,
    crackFreqEnd: 560,
    crackHighpass: 460,
    tail: 0.18,
    grit: 0.32,
  },
  flashScale: 0.62,
  flashColor: 0xffd79a,
  tracerColor: 0xffe6a8,
  tracerWidth: 0.012,
  tracerChance: 0.22,
  ejectsShells: true,
  shellScale: 0.75,
  flashLightIntensity: 4.5,
  crosshairGap: 11,
  description: 'Full-auto sidearm with a savage cyclic rate. Empties a magazine in a second — control it in bursts.',
};

export const REVOLVER: WeaponConfig = {
  id: 'revolver',
  name: 'Model 29 Magnum',
  category: 'REVOLVER',
  slot: 3,

  damage: 78,
  headshotMultiplier: 2.2,
  limbMultiplier: 0.8,
  pellets: 1,
  pelletSpread: 0,
  falloffStart: 30,
  falloffEnd: 70,
  minDamageScale: 0.65,
  penetration: 1,
  penetrationDamageScale: 0.55,
  muzzleVelocity: 460,

  rpm: 160,
  fireModes: ['semi'],
  burstCount: 1,
  burstDelay: 0,
  actionType: 'cylinder',
  cycleTime: 0,

  magSize: 6,
  reserveAmmo: 36,
  maxReserveAmmo: 48,
  reloadTime: 2.5,
  reloadEmptyTime: 2.9,
  shellReload: false,
  shellReloadTime: 0,

  drawTime: 0.5,
  holsterTime: 0.32,
  adsTime: 0.2,
  adsFovScale: 0.78,
  adsMoveScale: 0.6,
  weightMoveScale: 0.99,

  spread: {
    hip: 2.2,
    ads: 0.2,
    moving: 1.7,
    jumping: 4.5,
    crouchScale: 0.68,
    perShot: 1.1,
    recovery: 4,
    max: 6,
  },
  recoil: {
    vertical: 2.6,
    horizontal: 0.8,
    randomness: 0.4,
    recovery: 6,
    permanence: 0.25,
    kickback: 0.05,
    modelPitch: 16,
    shake: 1.0,
  },
  viewModel: {
    hipOffset: [0.0, -0.005, 0.0],
    hipRotation: [0, 0, 0],
    adsDistance: 0.3,
    swayScale: 1.05,
    scale: 1,
  },

  audio: {
    gain: 0.9,
    bodyFreq: 220,
    bodyEndFreq: 50,
    bodyDecay: 0.2,
    crackDecay: 0.16,
    crackFreqStart: 7400,
    crackFreqEnd: 300,
    crackHighpass: 240,
    tail: 0.7,
    grit: 0.45,
  },
  flashScale: 1.3,
  flashColor: 0xffb055,
  tracerColor: 0xffdca0,
  tracerWidth: 0.02,
  tracerChance: 0.6,
  ejectsShells: false,
  shellScale: 1.1,
  flashLightIntensity: 11,
  crosshairGap: 8,
  description: 'Six rounds of hand cannon. Slow, loud and unforgiving, but almost anything it touches goes down.',
};

export const DMR: WeaponConfig = {
  id: 'dmr',
  name: 'SR-25 Marksman',
  category: 'DMR',
  slot: 6,

  damage: 62,
  headshotMultiplier: 2.0,
  limbMultiplier: 0.8,
  pellets: 1,
  pelletSpread: 0,
  falloffStart: 90,
  falloffEnd: 200,
  minDamageScale: 0.75,
  penetration: 2,
  penetrationDamageScale: 0.7,
  muzzleVelocity: 840,

  rpm: 320,
  fireModes: ['semi'],
  burstCount: 1,
  burstDelay: 0,
  actionType: 'gas',
  cycleTime: 0,

  magSize: 20,
  reserveAmmo: 120,
  maxReserveAmmo: 160,
  reloadTime: 2.4,
  reloadEmptyTime: 3.0,
  shellReload: false,
  shellReloadTime: 0,

  drawTime: 0.65,
  holsterTime: 0.4,
  adsTime: 0.32,
  adsFovScale: 0.45,
  scopeFov: 26,
  adsMoveScale: 0.45,
  weightMoveScale: 0.9,

  spread: {
    hip: 3.2,
    ads: 0.05,
    moving: 2.4,
    jumping: 6.0,
    crouchScale: 0.55,
    perShot: 0.8,
    recovery: 4.5,
    max: 7,
  },
  recoil: {
    vertical: 1.9,
    horizontal: 0.5,
    randomness: 0.35,
    recovery: 6.5,
    permanence: 0.25,
    kickback: 0.038,
    modelPitch: 10,
    shake: 0.8,
  },
  viewModel: {
    hipOffset: [0.0, 0.0, -0.02],
    hipRotation: [0, 0, 0],
    adsDistance: 0.4,
    swayScale: 0.8,
    scale: 1,
  },

  audio: {
    gain: 0.86,
    bodyFreq: 245,
    bodyEndFreq: 52,
    bodyDecay: 0.18,
    crackDecay: 0.15,
    crackFreqStart: 8600,
    crackFreqEnd: 320,
    crackHighpass: 250,
    tail: 0.6,
    grit: 0.45,
  },
  flashScale: 1.15,
  flashColor: 0xffb84f,
  tracerColor: 0xfff2b0,
  tracerWidth: 0.02,
  tracerChance: 0.7,
  ejectsShells: true,
  shellScale: 1.1,
  flashLightIntensity: 11,
  crosshairGap: 10,
  description: 'Scoped semi-automatic marksman rifle. Bridges the gap between the carbine and the bolt gun.',
};

export const LMG: WeaponConfig = {
  id: 'lmg',
  name: 'M249 Support',
  category: 'LMG',
  slot: 8,

  damage: 30,
  headshotMultiplier: 1.5,
  limbMultiplier: 0.9,
  pellets: 1,
  pelletSpread: 0,
  falloffStart: 45,
  falloffEnd: 110,
  minDamageScale: 0.55,
  penetration: 2,
  penetrationDamageScale: 0.6,
  muzzleVelocity: 900,

  rpm: 780,
  fireModes: ['auto'],
  burstCount: 1,
  burstDelay: 0.08,
  actionType: 'gas',
  cycleTime: 0,

  magSize: 100,
  reserveAmmo: 200,
  maxReserveAmmo: 300,
  reloadTime: 5.4,
  reloadEmptyTime: 6.4,
  shellReload: false,
  shellReloadTime: 0,

  drawTime: 0.95,
  holsterTime: 0.55,
  adsTime: 0.42,
  adsFovScale: 0.8,
  adsMoveScale: 0.4,
  weightMoveScale: 0.8,

  spread: {
    hip: 4.5,
    ads: 0.55,
    moving: 2.6,
    jumping: 7.0,
    crouchScale: 0.55,
    perShot: 0.22,
    recovery: 5,
    max: 8,
  },
  recoil: {
    vertical: 0.75,
    horizontal: 0.55,
    randomness: 0.7,
    recovery: 7,
    permanence: 0.15,
    kickback: 0.024,
    modelPitch: 5.5,
    shake: 0.55,
  },
  viewModel: {
    hipOffset: [0.0, -0.005, -0.02],
    hipRotation: [0, 0, 0],
    adsDistance: 0.42,
    swayScale: 0.65,
    scale: 1,
  },

  audio: {
    gain: 0.8,
    bodyFreq: 210,
    bodyEndFreq: 55,
    bodyDecay: 0.12,
    crackDecay: 0.1,
    crackFreqStart: 8000,
    crackFreqEnd: 360,
    crackHighpass: 270,
    tail: 0.5,
    grit: 0.5,
  },
  flashScale: 1.2,
  flashColor: 0xffb24d,
  tracerColor: 0xff9a5a,
  tracerWidth: 0.02,
  tracerChance: 0.75,
  ejectsShells: true,
  shellScale: 1.05,
  flashLightIntensity: 10,
  crosshairGap: 14,
  description: 'Belt-fed suppression. A hundred rounds of sustained fire, glacial reloads and a bipod you will want to use.',
};

export const AUTO_SHOTGUN: WeaponConfig = {
  id: 'autoShotgun',
  name: 'AA-12 Sweeper',
  category: 'AUTO SHOTGUN',
  slot: 10,

  damage: 11,
  headshotMultiplier: 1.3,
  limbMultiplier: 0.9,
  pellets: 8,
  pelletSpread: 3.0,
  falloffStart: 7,
  falloffEnd: 24,
  minDamageScale: 0.12,
  penetration: 0,
  penetrationDamageScale: 0.3,
  muzzleVelocity: 380,

  rpm: 300,
  fireModes: ['auto', 'semi'],
  burstCount: 1,
  burstDelay: 0.1,
  actionType: 'gas',
  cycleTime: 0,

  magSize: 12,
  reserveAmmo: 48,
  maxReserveAmmo: 72,
  reloadTime: 2.6,
  reloadEmptyTime: 3.2,
  shellReload: false,
  shellReloadTime: 0,

  drawTime: 0.7,
  holsterTime: 0.45,
  adsTime: 0.3,
  adsFovScale: 0.88,
  adsMoveScale: 0.58,
  weightMoveScale: 0.88,

  spread: {
    hip: 1.8,
    ads: 0.9,
    moving: 1.2,
    jumping: 3.5,
    crouchScale: 0.85,
    perShot: 0.42,
    recovery: 4.5,
    max: 5,
  },
  recoil: {
    vertical: 2.0,
    horizontal: 0.8,
    randomness: 0.45,
    recovery: 6.5,
    permanence: 0.18,
    kickback: 0.042,
    modelPitch: 10,
    shake: 0.9,
  },
  viewModel: {
    hipOffset: [0.0, -0.005, -0.02],
    hipRotation: [0, 0, 0],
    adsDistance: 0.36,
    swayScale: 0.85,
    scale: 1,
  },

  audio: {
    gain: 0.82,
    bodyFreq: 158,
    bodyEndFreq: 42,
    bodyDecay: 0.18,
    crackDecay: 0.14,
    crackFreqStart: 5600,
    crackFreqEnd: 220,
    crackHighpass: 165,
    tail: 0.5,
    grit: 0.55,
  },
  flashScale: 1.35,
  flashColor: 0xffa348,
  tracerColor: 0xffc688,
  tracerWidth: 0.011,
  tracerChance: 0.12,
  ejectsShells: true,
  shellScale: 1.35,
  flashLightIntensity: 11,
  crosshairGap: 20,
  description: 'Fully automatic buckshot from a drum. Clears a room in half a second and empties itself just as fast.',
};

export const WEAPON_CONFIGS: Record<WeaponId, WeaponConfig> = {
  pistol: PISTOL,
  machinePistol: MACHINE_PISTOL,
  revolver: REVOLVER,
  smg: SMG,
  rifle: RIFLE,
  dmr: DMR,
  sniper: SNIPER,
  lmg: LMG,
  shotgun: SHOTGUN,
  autoShotgun: AUTO_SHOTGUN,
};

/**
 * Loadout order, mirrored by the slot keys 1-9 and 0 and by scroll cycling.
 * Weapons are grouped from lightest to heaviest so scrolling walks the arsenal
 * in a sensible order.
 */
export const WEAPON_ORDER: readonly WeaponId[] = [
  'pistol',
  'machinePistol',
  'revolver',
  'smg',
  'rifle',
  'dmr',
  'sniper',
  'lmg',
  'shotgun',
  'autoShotgun',
];
